Repository FRONT-END-BOOTCAMP-PLUS-4/room-to-be, pull requests merged in 2025-05, with the labels that each got.

#8 R2B-03-OverflowMenuComponent
  app/components/list/Card.tsx
  app/components/list/SavedRoomCard.tsx
  app/components/overflowmenu/OverflowMenu.tsx
  public/assets/icons/more.svg
Labels: ✨ Feature, 🎨 UI

#13 R2B-05-FurnitureModel,FurnitureListComponent
  app/simulator/components/furnitures/FurnitureList.tsx
  app/simulator/components/furnitures/FurnitureModel.tsx
  app/simulator/page.tsx
  public/assets/models/ikea.png
  public/assets/models/ikea_cart.glb
  public/assets/models/table.glb
  stores/useFurnitureStore.tsx
Labels: ✨ Feature

#19 R2B-14-ModalComponents
  app/components/list/TemplateCard.tsx
  app/components/modal/InteriorStartModal.tsx
  app/components/modal/LabeledNumberInput.tsx
  app/components/modal/Modal.tsx
  app/components/modal/ModalController.tsx
  app/components/modal/RoomSizeModal.tsx
  app/components/modal/StartModalItem.tsx
  app/components/modal/TemplateSelectModal.tsx
  public/assets/images/newroom.png
  public/assets/images/template.png
Labels: ✨ Feature, 🎨 UI

#20 R2B-12-SpaceSimulation
  app/simulator/components/room/CameraButtons.tsx
  app/simulator/components/room/CameraController.tsx
  app/simulator/components/room/Wall.tsx
  app/simulator/page.tsx
  stores/useViewStore.tsx
Labels: 🐞 Bug, ✨ Feature, ♻️ Refactor

#18 R2B-05-FurnitureScale
  app/hooks/useCursorOnDrag.ts
  app/hooks/useFormatToThreeDigitInt.ts
  app/hooks/useGetBaseSize.ts
  app/hooks/useHighlightMaterial.ts
  app/hooks/useSyncRotationFromStore.ts
  app/hooks/useSyncScaleFromStore.ts
  app/simulator/components/furnitures/FurnitureController.tsx
  app/simulator/components/furnitures/FurnitureControllerBtn.tsx
  app/simulator/components/furnitures/FurnitureList.tsx
  app/simulator/components/furnitures/FurnitureModel.tsx
  app/simulator/components/furnitures/FurnitureSizeInput.tsx
  app/simulator/components/furnitures/FurnitureThumbnailInfo.tsx
  app/simulator/components/furnitures/LockedScaleSlider.tsx
  app/simulator/components/furnitures/ScaleLockToggle.tsx
  app/simulator/components/furnitures/UnlockedScaleInputs.tsx
  app/simulator/page.tsx
  components/ui/slider.tsx
  package.json
  public/assets/icons/rotate-left.svg
  public/assets/icons/rotate-right.svg
  public/assets/icons/view-mode.svg
  public/assets/models/banker_lamp.glb
  stores/useFurnitureStore.tsx
Labels: ✨ Feature, 🎨 UI

#23 R2B-05-FurniturePosition
  app/hooks/useDragPosition.ts
  app/hooks/useFormatToThreeDigitInt.ts
  app/hooks/useGetBaseSize.ts
  app/simulator/components/furnitures/FurnitureController.tsx
  app/simulator/components/furnitures/FurnitureList.tsx
  app/simulator/components/furnitures/FurnitureModel.tsx
  app/simulator/components/furnitures/LockedScaleSlider.tsx
  app/simulator/components/furnitures/UnlockedScaleInputs.tsx
  app/simulator/page.tsx
  app/types/furniture.ts
  public/assets/models/window.glb
  stores/useFurnitureStore.tsx
  stores/useViewStore.tsx
Labels: ✨ Feature, ⏳ In progress

#25 R2B-12-RoomExperience
  app/simulator/components/furnitures/FurnitureController.tsx
  app/simulator/components/furnitures/FurnitureControllerBtn.tsx
Labels: ♻️ Refactor

#27 R2B-05-FurnitureControl
  app/hooks/useDragPosition.ts
  app/hooks/useResettableFurniture.ts
  app/hooks/useSyncPositionFromStore.ts
  app/hooks/useSyncRotationFromStore.ts
  app/simulator/components/furnitures/FurnitureController.tsx
  app/simulator/components/furnitures/FurnitureControllerBtn.tsx
  app/simulator/components/furnitures/FurnitureModel.tsx
  app/simulator/page.tsx
  app/types/furniture.ts
  stores/useFurnitureStore.tsx
Labels: ✨ Feature

#30 R2B-12-RoomExperience
  app/(user)/list/page.tsx
  app/api/rooms/[id]/route.ts
  app/components/modal/LabeledNumberInput.tsx
  app/components/modal/RoomSizeModal.tsx
  app/components/modal/page.tsx
  app/hooks/useResettableFurniture.ts
  app/hooks/useRoomSizeForm.ts
  app/hooks/useSyncPositionFromStore.ts
  app/layout.tsx
  app/not-found.tsx
  app/simulator/components/room/CameraController.tsx
  app/simulator/components/room/Wall.tsx
  app/simulator/page.tsx
  public/favicon_io/android-chrome-192x192.png
  public/favicon_io/android-chrome-512x512.png
  public/favicon_io/apple-touch-icon.png
  public/favicon_io/favicon-16x16.png
  public/favicon_io/favicon-32x32.png
  public/favicon_io/favicon.ico
  stores/useFurnitureStore.tsx
  stores/useRoomSizeStore.tsx
  utils/roomSizeConstants.ts
  utils/roomSizeValidators.ts
Labels: 🐞 Bug, ✨ Feature, ⏳ In progress

#32 R2B-11-LandingPage
  app/components/Header.tsx
  app/components/landing/CarouselSlideItem.tsx
  app/components/landing/CarouselSlider.tsx
  app/components/landing/Landing01.tsx
  app/components/landing/Preview3DButton.tsx
  app/globals.css
  app/page.tsx
  components/ui/progress.tsx
  hooks/useSliderProgress.ts
  package.json
  public/assets/images/main-room01.png
  public/assets/images/main-room02.png
  public/assets/images/main-room03.png
  public/assets/images/main-room04.png
  public/assets/images/room01-box.png
  public/assets/images/room02-box.png
  public/assets/images/room03-box.png
  public/assets/images/room04-box.png
  tailwind.config.ts
Labels: ✨ Feature

#35 R2B-05-CollisionDetection
  app/hooks/useDragPosition.ts
  app/hooks/useFurnitureCollision.ts
  app/simulator/page.tsx
  backend/infra/db/prisma/schema.prisma
  utils/collisionUtils.ts
Labels: ✨ Feature, ⏳ In progress

#38 R2B-37-GlobalsCss
  app/globals.css
Labels: 🐞 Bug

#39 R2B-31-InsertFurniture
  apis/furnitures.ts
  app/api/furnitures/route.ts
  app/simulator/components/sidebar/FurnitureSidebar.tsx
  app/simulator/page.tsx
  backend/domain/entities/Furniture.ts
  backend/dto/FurnitureDto.ts
  backend/infra/db/prisma/migrations/20250521075423_first_migration/migration.sql
  backend/infra/db/prisma/schema.prisma
  backend/infra/db/prisma/seed.js
  backend/usecase/furniture/CreateFurniture.ts
  backend/utils/mapper.ts
Labels: ✨ Feature

#41 R2B-12-RoomExperience
  app/components/landing/Preview3DButton.tsx
  app/components/loading/GlobalLoadingProvider.tsx
  app/components/loading/Loading.tsx
  app/components/loading/page.tsx
  app/components/modal/RoomSizeModal.tsx
  app/hooks/useLoading.ts
  app/layout.tsx
  app/simulator/page.tsx
  package.json
  stores/useLoadingStore.tsx
Labels: ✨ Feature

#48 R2B-28-SocialLogin
  app/(anon)/login/gitkeep
  app/(anon)/login/page.tsx
  app/api/auth/[...nextauth]/route.ts
  app/components/Header.tsx
  app/components/landing/CarouselSlideItem.tsx
  app/layout.tsx
  app/page.tsx
  auth.ts
  backend/infra/db/prisma/schema.prisma
  middleware.ts
  package.json
  public/assets/icons/google-logo.svg
  public/assets/icons/kakao.png
Labels: ✨ Feature

#45 R2B-33-BackgroundEffects
  app/hooks/useHighlightMaterial.ts
  app/hooks/useLampEmissiveMaterial.ts
  app/hooks/useLampLight.ts
  app/simulator/components/furnitures/FurnitureController.tsx
  app/simulator/components/furnitures/FurnitureModel.tsx
  app/simulator/components/room/BackgroundController.tsx
  app/simulator/components/room/BackgroundSelector.tsx
  app/simulator/components/room/CameraController.tsx
  app/simulator/components/room/Floor.tsx
  app/simulator/components/room/Lighting.tsx
  app/simulator/components/room/Room.tsx
  app/simulator/components/room/RoomShadow.tsx
  app/simulator/page.tsx
  eslint.config.js
  stores/useBackgroundStore.tsx
  stores/useFurnitureStore.tsx
  stores/useLightingStore.tsx
  stores/useViewStore.tsx
Labels: ✨ Feature

#46 R2B-12-RoomExperience
  app/simulator/components/room/Lighting.tsx
  app/simulator/page.tsx
  public/assets/images/line-pattern-wall.jpg
  public/assets/images/white-wall.png
  public/assets/images/white-wood-floor.png
Labels: ✨ Feature

#52 R2B-50-AuthHandling
  app/components/login/LoginRedirectModal.tsx
  app/components/login/Portal.tsx
  app/layout.tsx
  app/simulator/SimulatorPage.tsx
  auth.ts
  stores/useLoginRedirectModalStore.ts
Labels: ✨ Feature

#61 R2B-54-LandingUpdate
  app/components/landing/CarouselSlideItem.tsx
  app/components/landing/CarouselSlider.tsx
  app/page.tsx
Labels: 🐞 Bug, 🎨 UI

#64 R2B-59-SimulatorPolish
  app/(user)/list/components/RoomList.tsx
  app/(user)/list/page.tsx
  app/components/list/SavedRoomCard.tsx
  app/simulator/SimulatorPage.tsx
  app/simulator/components/furnitures/EmptyFurnitureModal.tsx
  app/simulator/components/furnitures/FurnitureModel.tsx
  app/simulator/components/room/RoomEditModal.tsx
  app/simulator/components/room/RoomSaveModal.tsx
  app/simulator/components/sidebar/FurnitureGroupList.tsx
  app/simulator/components/sidebar/FurnitureSidebar.tsx
  app/simulator/components/sidebar/FurnitureThumbnail.tsx
  components/ui/dialog.tsx
  package.json
  stores/useFurnitureStore.tsx
Labels: 🐞 Bug, ✨ Feature
