Repository FRONT-END-BOOTCAMP-PLUS-4/room-to-be, pull requests merged in 2025-06, with the labels that each got.

#67 R2B-65-MinorFunctionalUpdate
  app/(anon)/login/page.tsx
  app/simulator/SimulatorPage.tsx
  app/simulator/components/sidebar/FurnitureSidebar.tsx
  middleware.ts
Labels: 🐞 Bug, ♻️ Refactor

#73 R2B-54-LandingUpdate
  app/components/buttons/BoxTextButton.tsx
  app/components/landing/CarouselSlideItem.tsx
  app/components/landing/CarouselSlider.tsx
  app/components/modal/InteriorStartModal.tsx
  app/components/modal/Modal.tsx
  app/components/modal/ModalController.tsx
  app/components/modal/RoomSizeModal.tsx
  app/components/modal/TemplateSelectModal.tsx
  app/components/modal/page.tsx
  app/page.tsx
  app/simulator/SimulatorPage.tsx
  app/simulator/components/furnitures/FurnitureController.tsx
  app/simulator/components/room/CameraController.tsx
  components/ui/progress.tsx
  public/assets/images/main-room02.png
  public/assets/images/main-room03.png
  public/assets/images/room01-box.png
  public/assets/images/room02-box.png
  public/assets/images/room03-box.png
  public/assets/images/room04-box.png
  tailwind.config.ts
Labels: 🐞 Bug, ✨ Feature

#76 R2B-54-LandingUpdate
  app/components/landing/CarouselSlideItem.tsx
  app/hooks/useLampLight.ts
  app/simulator/components/furnitures/FurnitureModel.tsx
Labels: 🎨 UI

#79 R2B-54-LandingUpdate
  app/components/landing/CarouselSlideItem.tsx
  app/components/landing/CarouselSlider.tsx
  app/page.tsx
Labels: 🐞 Bug, 🎨 UI, ♻️ Refactor
